[package]
name = "rustystore-macros"
version = "0.1.0"
edition = "2021"
description = "macros for RustyStore"
license = "GPL-3.0"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
